### PR TITLE
bumped sbt versions to 0.13.8 fixes #85

### LINKED ISSUE #85: Upgrade to sbt 0.13.9
Using gradle as build tool and zinc as default scala compiler. However, latest published zinc 0.3.7 depends on sbt that does not contain fix for https://github.com/sbt/sbt/issues/1655

PR to follow

### PR DESCRIPTION
**Pull request by sirocchj**
Fixes #85 
Following up on https://twitter.com/JSirocchi/status/639077915821477888

### CODE REVIEW

**Comment by IainHull** [comment]
This change would really help us out.  Currently our gradle build has to use the scala ant task to build with macro paradise.  Incremental compilation is very buggy in the ant task and we desperately want to move back to zinc.

**Comment by eed3si9n** [comment]
Could you update the title to "0.13.8"?

**Comment by dwijnand** [comment]
What was wrong with 0.13.9?

**Comment by sirocchj** [comment]
```method distinctParser in object Defaults cannot be accessed in object sbt.Defaults```

**Comment by eed3si9n** [comment]
@dwijnand See the travis failure.

**Comment by dwijnand** [comment]
yeah.. https://github.com/sbt/sbt/pull/1970/files#diff-6373e7f7122325e753b75fe1cc76ff5fR902

**Comment by eed3si9n** [comment]
@dwijnand we can copy-pasta the parser code once we release zinc 0.13.8.

**Comment by dwijnand** [comment]
Sure. LGTM.

**Comment by sirocchj** [comment]
need to squash or can be merged as is? I've signed the CLA in the meantime anyway

**Comment by eed3si9n** [comment]
LGTM

**Pull request merged**
