### PR TITLE
0.3.8.1

### PR DESCRIPTION
**Pull request by eed3si9n**
Ref #85, #86

### CODE REVIEW

**Comment by eed3si9n** [comment]
uh oh:

```
[error]   [info] 'compiler-interface' not yet compiled for Scala 2.10.4. Compiling...
[error]   /tmp/sbt_23dfbf29/xsbt/ExtractAPI.scala:22: error: ']' expected but $XMLSTART$< found.
[error]   class ExtractAPI[GlobalType <: CallbackGlobal](val global: GlobalType,
[error]                               ^
```

**Comment by dwijnand** [comment]
LGTM

**Comment by SethTisue** [comment]
I'm having trouble following all the twists and turns around SI-9027. I'd like to understand why 5bf1ec533509415ea41a8c88622b4b0d051de29c is necessary?

**Comment by dwijnand** [comment]
sbt 0.13.8 is Scala 2.10.4, and 0.13.9 is 2.10.5, FWIW, not sure if that helps.

**Comment by SethTisue** [comment]
Oh, right, duh. OK, yes, that's sufficient explanation.

**Pull request merged**
