### PR TITLE
Grzegorz -> Adriaan in README

### PR DESCRIPTION
**Pull request by SethTisue**
review/merge by @adriaanm

### CODE REVIEW

**Comment by adriaanm** [comment]
LGTM :)

**Comment by SethTisue** [comment]
@adriaanm I don't have the access rights to merge it myself

**Comment by SethTisue** [comment]
haha oh no "[GitHub] Subscribed to 88 repositories" well I asked for it :-)

**Comment by adriaanm** [comment]
a definite case of careful what you wish for :smiling_imp:

**Comment by wsargent** [comment]
I'm still unwatching repositories from a month ago...

**Pull request merged**
