### PR TITLE
Bump zinc version to 0.3.8-SNAPSHOT

### PR DESCRIPTION
**Pull request by gkossakowski**
Also, update to latest stable sbt dependency: 0.13.7.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Review by @pdalpra

**Comment by pdalpra** [comment]
Well nothing against it :)
Apart from a minor question : Why bumping to 0.3.8 instead of 0.3.7 ?

**Comment by gkossakowski** [comment]
Because 0.3.7 is already published: https://github.com/typesafehub/zinc/releases/tag/v0.3.7

**Comment by pdalpra** [comment]
OK, I didn't see that.

**Pull request merged**
