### PR TITLE
Publishing cleanups

### PR DESCRIPTION
**Pull request by gkossakowski**
Fix publishing settings. Check commit message for details.

Also, update README file with latest information on building distribution.

### CODE REVIEW

**Comment by gkossakowski** [comment]
Review by @pdalpra

**Comment by gkossakowski** [comment]
//cc @jsuereth

**Comment by gkossakowski** [comment]
FYI: I published 0.3.6 release based on this changes. The tag has been pushed already.

**Comment by pdalpra** [comment]
LGTM, since `publishTo` is set for publishing the JARs and pom.xml through `Publish.scala` and that `publishTo` was effectively unused.

Moreover, it could have lead someday to failures if `Dist.settings` were added after `Publish.settings`, overriding the correct `publishTo` with the old, incorrect one.

Clean up + preemptive bug-fixing :)

**Comment by gkossakowski** [comment]
Thanks for the review! I'm glad we sorted out all the issues within one day! :+1:

**Comment by pdalpra** [comment]
I'm glad that I could help you :)

**Pull request merged**
